spring:
  jackson:
    time-zone: Asia/Seoul
  # swagger

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: 3.39.190.50  # Redis 서버의 호스트 주소를 설정
      port: 6379       # Redis 서버가 수신 대기하는 포트를 설정
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    defer-datasource-initialization: true  # data.sql 실행 시점 조정
  sql:
    init:
      mode: always
#      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: ${ADMIN_EMAIL}
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 1000
  refresh-token-expiration-minutes: 4200
springdoc:
  default-flat-param-object: true
  use-fqn: true
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    try-it-out-enabled: true
file:
  upload-dir: /app/fileImage
  default-image: http://ec2-3-39-190-50.ap-northeast-2.compute.amazonaws.com:8080/images/noImage.png
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_BUCKET_NAME}
    stack:
      auto: false